
export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const SET_ERROR = "SET_ERROR"
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS"
export const PURCHASE_FAIL = "PURCHASE_FAIL"
export const PURCHASE_START = "PURCHASE_START"
export const PURCHASE_INIT = "PURCHASE_INIT"
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';